title: My Modern Blog
description: A minimalist blog template.

baseurl: ""
url: "https://classy-jelly-03b905.netlify.app"

# Theme
remote_theme: jekyll/minima

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme