backend:
  name: git-gateway
  repo: sano2019/blog_template # Update this!
  branch: main
  identity_url: https://classy-jelly-03b905.netlify.app/.netlify/identity
  gateway_url: https://classy-jelly-03b905.netlify.app/.netlify/git

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }